// Mocks generated by Mockito 5.4.4 from annotations
// in value_filter/test/services/chinese_ocr_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:value_filter/services/chinese_ocr/chinese_ocr_providers.dart' as _i2;
import 'package:value_filter/abstract/ocr_service.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BaiduOcrService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaiduOcrService extends _i1.Mock implements _i2.BaiduOcrService {
  MockBaiduOcrService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i5.OcrResult> recognize(_i4.Uint8List? imageData) =>
      (super.noSuchMethod(
        Invocation.method(
          #recognize,
          [imageData],
        ),
        returnValue: _i3.Future<_i5.OcrResult>.value(_i5.OcrResult(
          fullText: '',
          blocks: [],
          confidence: 0.0,
          language: '',
        )),
      ) as _i3.Future<_i5.OcrResult>);
}

/// A class which mocks [TencentOcrService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTencentOcrService extends _i1.Mock implements _i2.TencentOcrService {
  MockTencentOcrService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i5.OcrResult> recognize(_i4.Uint8List? imageData) =>
      (super.noSuchMethod(
        Invocation.method(
          #recognize,
          [imageData],
        ),
        returnValue: _i3.Future<_i5.OcrResult>.value(_i5.OcrResult(
          fullText: '',
          blocks: [],
          confidence: 0.0,
          language: '',
        )),
      ) as _i3.Future<_i5.OcrResult>);
}
